"use client";

import { useGenerateInspirationRedesign } from "@/lib/api";
import { useState } from "react";
import { FurnitureIdentificationPanel } from "./FurnitureIdentificationPanel";

interface InspirationRedesignDisplayProps {
  projectId: string;
  generatedImageBase64?: string;
  inspirationPrompt?: string;
  hasRecommendations: boolean;
}

export function InspirationRedesignDisplay({
  projectId,
  generatedImageBase64,
  inspirationPrompt,
  hasRecommendations,
}: InspirationRedesignDisplayProps) {
  const generateRedesign = useGenerateInspirationRedesign();
  const [imageError, setImageError] = useState(false);
  const [showFurniturePanel, setShowFurniturePanel] = useState(false);

  const handleGenerate = () => {
    generateRedesign.mutate(projectId, {
      onError: (error) => {
        console.error("Failed to generate inspiration redesign:", error);
        alert("Failed to generate inspiration redesign. Please try again.");
      },
    });
  };

  return (
    <div className="mt-8 bg-white dark:bg-gray-800 rounded-lg shadow-lg p-6">
      <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-4">
        Inspiration-based Redesign
      </h2>

      {!generatedImageBase64 && (
        <div className="space-y-4">
          <p className="text-gray-600 dark:text-gray-300">
            Generate a new image that applies your inspiration recommendations to
            the original room image while preserving its structure.
          </p>
          <button
            onClick={handleGenerate}
            disabled={
              generateRedesign.isPending || !hasRecommendations
            }
            className="px-6 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 disabled:opacity-50 disabled:cursor-not-allowed"
          >
            {generateRedesign.isPending
              ? "Generating..."
              : "Generate Inspiration Redesign"}
          </button>
          {!hasRecommendations && (
            <p className="text-sm text-gray-500 dark:text-gray-400">
              Add inspiration images and generate recommendations first.
            </p>
          )}
        </div>
      )}

      {generatedImageBase64 && (
        <div className="mt-6">
          <h3 className="font-semibold text-gray-900 dark:text-white mb-3">
            AI Redesigned Room
          </h3>
          <div className="bg-gray-50 dark:bg-gray-700 rounded-lg p-4">
            {!imageError ? (
              <img
                src={`data:image/png;base64,${generatedImageBase64}`}
                alt="Inspiration Redesign"
                className="w-full h-64 object-cover rounded-lg mb-3"
                onError={() => setImageError(true)}
              />
            ) : (
              <div className="w-full h-64 bg-gray-200 dark:bg-gray-600 rounded-lg mb-3 flex items-center justify-center">
                <div className="text-center">
                  <svg
                    className="w-12 h-12 text-gray-400 mx-auto mb-2"
                    fill="none"
                    stroke="currentColor"
                    viewBox="0 0 24 24"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth={2}
                      d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
                    />
                  </svg>
                  <p className="text-gray-500 dark:text-gray-400 text-sm">
                    Failed to load redesign image
                  </p>
                </div>
              </div>
            )}
            <p className="font-medium text-gray-900 dark:text-white text-sm">
              Generated by Gemini AI using your inspiration
            </p>
          </div>

          {/* AI Furniture Identification Button */}
          <div className="mt-6 p-4 bg-gradient-to-r from-purple-50 to-indigo-50 dark:from-purple-900/20 dark:to-indigo-900/20 rounded-lg">
            <div className="flex items-center justify-between">
              <div className="flex-1">
                <h4 className="font-semibold text-gray-900 dark:text-white mb-1">
                  🔍 Identify Furniture with AI
                </h4>
                <p className="text-sm text-gray-600 dark:text-gray-400">
                  Click to mark and identify multiple furniture items in the redesigned room
                </p>
              </div>
              <button
                onClick={() => setShowFurniturePanel(true)}
                className="px-6 py-2 bg-purple-600 text-white rounded-lg hover:bg-purple-700 font-medium"
              >
                Identify Furniture
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Furniture Identification Panel */}
      {showFurniturePanel && generatedImageBase64 && (
        <FurnitureIdentificationPanel
          projectId={projectId}
          imageBase64={generatedImageBase64}
          imageType="inspiration"
          onClose={() => setShowFurniturePanel(false)}
        />
      )}

      {inspirationPrompt && (
        <div className="mt-6 bg-indigo-50 dark:bg-indigo-900/20 rounded-lg p-4">
          <h4 className="font-medium text-indigo-900 dark:text-indigo-200 mb-2">
            Prompt Used:
          </h4>
          <p className="text-indigo-800 dark:text-indigo-300 text-sm">
            {inspirationPrompt}
          </p>
        </div>
      )}
    </div>
  );
}



